### ISSUE TITLE
Migration Directionality Inverted?

### ISSUE THREAD

**Issue by gollumsluvslave** [cskardon/CosmosToNeo4j#16]
Following a couple of test migrations, it appears that the direction of edges is inverted in Neo4J, from the direction they had in CosmosDB.

For example, in our Cosmos DB, we have an edge/rel labelled 'Themes' that goes out from Client node in to Theme nodes in Comsos, but, one imported into Neo4J, the relation Themes direction goes from Theme to Client.

This seems consistent across the migration from what I can see.

**Comment by cskardon** [comment]
Hi, I've just committed #09f4a19ca6ad487a0aded7dc49674d8688dbcb65  which fixes this - it was inverted for all use cases :/
